import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class RecipientInfo {
  getRecipient() {
    let recipient = {
      navigationField: {
        selectedIndex: 0,
        breadcrumbUrls: [
          {
            name: 'Directory',
            path: 'select_student_recipients?isShowRelation=true&permission= ',
            index: 0,
          },
          {
            name: 'Class',
            path: 'select_student_recipients_by_class?userType=true&permission= ',
            index: 1,
          },
          {
            name: 'Dept',
            path: 'select_student_recipients_by_enrollment?isShowRelation=true&permission= ',
            index: 2,
          },
          {
            name: 'Query Reports',
            path: 'recipients_by_query_report?userType=1',
            index: 4,
          },
          {
            name: 'Custom Reports',
            path: 'recipients_by_custom_report?userType=1',
            index: 5,
          },
        ],
      },
      buttons: [
        {
          fieldTitle: 'Button Title',
          fieldName: 'buttonTitle',
          fieldValue: 'Add',
          fieldType: 'TEXT',
          hints: null,
          maxLength: 0,
          required: false,
          options: null,
        },
        {
          fieldTitle: 'Button Title',
          fieldName: 'buttonTitle',
          fieldValue: 'Close',
          fieldType: 'TEXT',
          hints: null,
          maxLength: 0,
          required: false,
          options: null,
        },
      ],
      addStudentsFromAllPagesSelectionField: null,
      columns: [
        {
          name: 'idNumber',
          title: 'Id Number',
          type: 'TEXT',
          alignment: 'LEFT',
        },
        {
          name: 'name',
          title: 'Name',
          type: 'TEXT',
          alignment: 'LEFT',
        },
        {
          name: 'homePhone',
          title: 'Home Phone',
          type: 'TEXT',
          alignment: 'LEFT',
        },
        {
          name: 'cellPhone',
          title: 'Cell Phone',
          type: 'TEXT',
          alignment: 'LEFT',
        },
        {
          name: 'email',
          title: 'Email',
          type: 'TEXT',
          alignment: 'LEFT',
        },
        {
          name: 'relations',
          title: 'Relations',
          type: 'CHECKBOX',
          alignment: 'LEFT',
        },
      ],
      allSelectionField: {
        fieldTitle: 'All Students',
        fieldName: 'all',
        fieldValue: 'All Students',
        fieldType: 'CHECKBOX',
        hints: null,
        maxLength: 0,
        required: false,
        options: null,
      },
      allrelationSelectionField: {
        fieldTitle: 'All Relations',
        fieldName: 'allrelation',
        fieldValue: 'All Relations',
        fieldType: 'CHECKBOX',
        hints: null,
        maxLength: 0,
        required: false,
        options: null,
      },
      studentRecipients: [
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4109587,
              userRole: 1,
              name: 'Abu Raihan',
              userRoleName: 'Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2209-6-2317',
          name: 'Raihan',
          homePhone: '',
          cellPhone: '01729625659',
          email: 'sdfrgthyjuk@email.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110059,
              userRole: 1,
              name: 'Rakib Hasan',
              userRoleName: 'Bn Bnb BnbStudent',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-7-2769',
          name: 'Rakib',
          homePhone: '',
          cellPhone: '',
          email: '',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4109610,
              userRole: 1,
              name: 'Arifur Rahman',
              userRoleName: 'Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2209-6-2339',
          name: 'Arifur',
          homePhone: '',
          cellPhone: '',
          email: 'test1011@gmail.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4108602,
              userRole: 1,
              name: 'Murad Ahmed',
              userRoleName: 'Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2204-7-1456',
          name: 'Murad',
          homePhone: '045362565',
          cellPhone: '01915362565',
          email: 'sdfdfg@email.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4108628,
              userRole: 1,
              name: 'Test Student 1006  End1006',
              userRoleName: 'Test Student 1006  End1006Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2204-6-1457',
          name: 'End1006, Test Student 1006 ',
          homePhone: '',
          cellPhone: '',
          email: 'teststudent1006@email.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110091,
              userRole: 1,
              name: 'Exro3331  Exro3331',
              userRoleName: 'Exro3331  Exro3331Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-3-2801',
          name: 'exro3331, exro3331 ',
          homePhone: '',
          cellPhone: '',
          email: 'exro3331@orbund.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110126,
              userRole: 1,
              name: 'Exro33316  Exro33316',
              userRoleName: 'Exro33316  Exro33316Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-7-2836',
          name: 'exro33316, exro33316 ',
          homePhone: '',
          cellPhone: '',
          email: 'exro33316@gmail.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110068,
              userRole: 1,
              name: 'Exro3333  Exro3333',
              userRoleName: 'Exro3333  Exro3333Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-7-2778',
          name: 'exro3333, exro3333 ',
          homePhone: '',
          cellPhone: '',
          email: 'exro3333@gmail.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110101,
              userRole: 1,
              name: 'Exro33331  Exro33331',
              userRoleName: 'Exro33331  Exro33331Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-3-2811',
          name: 'exro33331, exro33331 ',
          homePhone: '',
          cellPhone: '',
          email: 'exro33331@gmail.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110124,
              userRole: 1,
              name: 'Exro333314  Exro333314',
              userRoleName: 'Exro333314  Exro333314Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-3-2834',
          name: 'exro333314, exro333314 ',
          homePhone: '',
          cellPhone: '',
          email: 'exro333314@gmail.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110104,
              userRole: 1,
              name: 'Exro33334  Exro33334',
              userRoleName: 'Exro33334  Exro33334Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-3-2814',
          name: 'exro33334, exro33334 ',
          homePhone: '',
          cellPhone: '',
          email: 'exro33334@gmail.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110105,
              userRole: 1,
              name: 'Exro33335  Exro33335',
              userRoleName: 'Exro33335  Exro33335Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-3-2815',
          name: 'exro33335, exro33335 ',
          homePhone: '',
          cellPhone: '',
          email: 'exro33335@gmail.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110070,
              userRole: 1,
              name: 'Exro3334  Exro3334',
              userRoleName: 'Exro3334  Exro3334Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-3-2780',
          name: 'exro3334, exro3334 ',
          homePhone: '',
          cellPhone: '',
          email: 'exro3334@gmail.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4109391,
              userRole: 1,
              name: 'Exro45453  Exro45453',
              userRoleName: 'Exro45453  Exro45453Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2208-6-2131',
          name: 'exro45453, exro45453 ',
          homePhone: '',
          cellPhone: '',
          email: 'exro45453@email.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4109586,
              userRole: 1,
              name: 'Exrodfghjsfgh5  Exrodfghjsfgh5',
              userRoleName: 'Exrodfghjsfgh5  Exrodfghjsfgh5Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2209-6-2316',
          name: 'exrodfghjsfgh5, exrodfghjsfgh5 ',
          homePhone: '',
          cellPhone: '',
          email: 'sdfghjkl@email.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4109623,
              userRole: 1,
              name: 'Exroergthwefrg435  Exroergthwefrg435',
              userRoleName: 'Exroergthwefrg435  Exroergthwefrg435Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2209-7-2352',
          name: 'exroergthwefrg435, exroergthwefrg435 ',
          homePhone: '',
          cellPhone: '',
          email: 'exroergthwefrg435@email.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4109477,
              userRole: 1,
              name: 'Front1020  Front1020',
              userRoleName: 'Front1020  Front1020Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2208-6-2213',
          name: 'front1020, front1020 ',
          homePhone: '',
          cellPhone: '',
          email: 'front1020@email.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4109478,
              userRole: 1,
              name: 'Front1021  Front1021',
              userRoleName: 'Front1021  Front1021Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2208-6-2214',
          name: 'front1021, front1021 ',
          homePhone: '',
          cellPhone: '',
          email: 'front1021@email.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110004,
              userRole: 1,
              name: 'Test221026114237  Galactic',
              userRoleName: 'Test221026114237  GalacticStudent',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2210-7-2715',
          name: 'Galactic, Test221026114237 ',
          homePhone: '',
          cellPhone: '',
          email: 'shobuj.orbundqa@gmail.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110090,
              userRole: 1,
              name: 'Test221110131123 Middle Initial Galactic',
              userRoleName: 'Test221110131123 Middle Initial GalacticStudent',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-3-2800',
          name: 'Galactic, Test221110131123 Middle Initial',
          homePhone: 'Home Phone',
          cellPhone: 'Cell Phone',
          email: 'Test221110131123@student.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110082,
              userRole: 1,
              name: 'Sdfsdf  Sdfsdfsd',
              userRoleName: 'Sdfsdf  SdfsdfsdStudent',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-7-2792',
          name: 'sdfsdfsd, sdfsdf ',
          homePhone: '',
          cellPhone: '',
          email: 'shobuj.bangladesh.1971@gmail.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110003,
              userRole: 1,
              name: 'Test221026114035  Shopping',
              userRoleName: 'Test221026114035  ShoppingStudent',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2210-7-2714',
          name: 'Shopping, Test221026114035 ',
          homePhone: '',
          cellPhone: '',
          email: 'shobuj.orbundqa@gmail.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110110,
              userRole: 1,
              name: 'Test221113220327  Shopping',
              userRoleName: 'Test221113220327  ShoppingStudent',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-7-2820',
          name: 'Shopping, Test221113220327 ',
          homePhone: '',
          cellPhone: '',
          email: 'Test221113220327@student.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110130,
              userRole: 1,
              name: 'Std1606  Std1606',
              userRoleName: 'Std1606  Std1606Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-7-2840',
          name: 'std1606, std1606 ',
          homePhone: '',
          cellPhone: '',
          email: 'std1606@email.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110043,
              userRole: 1,
              name: 'Std950  Std950',
              userRoleName: 'Std950  Std950Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-3-2753',
          name: 'std950, std950 ',
          homePhone: '',
          cellPhone: '',
          email: 'shobuj.bangladesh.1971@gmail.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4109594,
              userRole: 1,
              name: 'Test220906143040  Student',
              userRoleName: 'Test220906143040  StudentStudent',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2209-6-2323',
          name: 'Student, Test220906143040 ',
          homePhone: '',
          cellPhone: '',
          email: 'Test220906143040@student.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110153,
              userRole: 1,
              name: 'Testss1036  Testss1036',
              userRoleName: 'Testss1036  Testss1036Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-3-2863',
          name: 'testss1036, testss1036 ',
          homePhone: '',
          cellPhone: '',
          email: '',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110155,
              userRole: 1,
              name: 'Testss1037  Testss1037',
              userRoleName: 'Testss1037  Testss1037Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-3-2865',
          name: 'testss1037, testss1037 ',
          homePhone: '',
          cellPhone: '',
          email: '',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4110156,
              userRole: 1,
              name: 'Testss1038  Testss1038',
              userRoleName: 'Testss1038  Testss1038Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2211-3-2866',
          name: 'testss1038, testss1038 ',
          homePhone: '',
          cellPhone: '',
          email: 'mashuk.orbund@gmail.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4109595,
              userRole: 1,
              name: 'Testtitle  Testtitle',
              userRoleName: 'Testtitle  TesttitleStudent',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2209-6-2324',
          name: 'testtitle, testtitle ',
          homePhone: '',
          cellPhone: '',
          email: 'testtitle@email.com',
          relations: [],
        },
        {
          selectionField: {
            fieldTitle: 'Selection Fields',
            fieldName: 'selectionFields',
            fieldValue: {
              userId: 4109584,
              userRole: 1,
              name: 'Ui32435465  Ui32435465',
              userRoleName: 'Ui32435465  Ui32435465Student',
            },
            fieldType: 'CHECKBOX',
            hints: null,
            maxLength: 0,
            required: false,
            options: null,
          },
          idNumber: '2209-6-2314',
          name: 'ui32435465, ui32435465 ',
          homePhone: '',
          cellPhone: '',
          email: 'ui32435465@email.com',
          relations: [],
        },
      ],
    };
    return recipient;
  }
}
