import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { SessionResolver } from '../resolvers/session.resolver';
import { TranslatorResolver } from '../resolvers/translator.resolver';
import { ClassListPage } from './class-list/class-list.page';
import { CourseDescriptionPage } from './course-description/course-description.page';
import { AddStudentMultiplePage } from './display-cart/add-student-multiple.page';
import { DisplayCartPage } from './display-cart/display-cart.page';
import { BillingPage } from './payment/billing.page';
import { CheckoutPage } from './payment/checkout.page';
import { AddStudentsPage } from './registration/add-students.page';
import { CreateAccountPage } from './registration/create-account.page';
import { LoginPage } from './registration/login.page';
import { RegistrationPage } from './registration/registration.page';
import { RequestPasswordPage } from './registration/request-password.page';
import { UpdateStudentPage } from './registration/update-student.page';
import { FilterResolver } from './resolvers/filter.resolver';
import { LocalStorageResolver } from './resolvers/local-storage.resolver';
import { OptionsResolver } from './resolvers/options.resolver';
import { ShoppingCartPage } from './shopping-cart.page';
import { ThankyouPage } from './thankyou/thankyou.page';
import { CART_URL } from './util/constant';

const classListWords = [
  'Filters',
  'Filter By',
  'About Course',
  'Select Class',
  'Clear all',
  'Courses',
  'Apply',
  'Search',
  'Start Date',
  'End Date',
  'Add to Cart',
  'title',
  'Passcode',
  'Invalid passcode.',
  'Enter Passcode',
  'Submit',
  'Cancel',
  'This class is full. You will be placed in waiting list.',
  'You will be placed in waiting list.',
  'Invalid date.',
  'Please add at least one student.',
  'Student must be',
  'years old to attend this class.',
  'First Name',
  'Last Name',
  'Date of Birth',
  'Email',
  'Add Student',
];

const routes = [
  {
    path: '',
    component: ShoppingCartPage,
    resolve: {
      sessionId: SessionResolver,
      translator: TranslatorResolver,
      option: OptionsResolver,
      localStorage: LocalStorageResolver,
    },
    data: {
      words: [
        'Your Cart',
        'Website',
        'Print This Page',
        'All',
        'Cancel',
        'Share',
        'Ok',
        'Confirm',
        'Add',
        'is invalid.',
        'This email already exists. Please use another email.',
        'is required.',
        'Remove',
      ],
    },
    children: [
      {
        path: `${CART_URL.course_link}/:id`,
        component: ClassListPage,
        resolve: {
          sessionId: SessionResolver,
          translator: TranslatorResolver,
          filter: FilterResolver,
        },
        data: {
          title: 'Course list with available classes',
          words: classListWords,
        },
      },
      {
        path: `${CART_URL.search_course_link}/:id`,
        component: ClassListPage,
        resolve: {
          sessionId: SessionResolver,
          translator: TranslatorResolver,
          filter: FilterResolver,
        },
        data: {
          title: 'Search course list with available classes',
          words: classListWords,
        },
      },
      {
        path: `${CART_URL.program_link}/:id`,
        component: ClassListPage,
        resolve: {
          sessionId: SessionResolver,
          translator: TranslatorResolver,
          filter: FilterResolver,
        },
        data: {
          title: 'Program list with courses',
          words: classListWords,
        },
      },
      {
        path: `${CART_URL.search_program_link}/:id`,
        component: ClassListPage,
        resolve: {
          sessionId: SessionResolver,
          translator: TranslatorResolver,
          filter: FilterResolver,
        },
        data: {
          title: 'Search program list with courses',
          words: classListWords,
        },
      },
      {
        path: `${CART_URL.course_description}/:id/:courseId`,
        component: CourseDescriptionPage,
        resolve: { sessionId: SessionResolver, translator: TranslatorResolver },
        data: {
          title: 'About course',
          words: [
            'Class List',
            'Select Class',
            'Website',
            'Cancel',
            'Share',
            'Share Course',
            'Share This Page',
            'Print This Page',
            'This course is a prerequisite for',
            'Prerequisite course(s)',
            'Recommended course(s) to take with this course',
            'Share Course',
            'Your Name',
            'Your Email',
            'Send to Email',
            'Subject',
            'Message',
            'This class is full. You will be placed in waiting list.',
            'You will be placed in waiting list.',
            'Invalid date.',
            'Please add at least one student.',
          ],
        },
      },
      {
        path: `${CART_URL.add_student_multiple}/:id`,
        component: AddStudentMultiplePage,
        resolve: { sessionId: SessionResolver, translator: TranslatorResolver },
        data: { title: 'Add student' },
        words: [
          'Add Student',
          'First Name',
          'Last Name',
          'Date of Birth',
          'Email',
          'email',
          'dateOfBirth',
          'firstName',
          'lastName',
        ],
      },
      {
        path: `${CART_URL.display_cart}/:id`,
        component: DisplayCartPage,
        resolve: { sessionId: SessionResolver, translator: TranslatorResolver },
        data: {
          title: 'Display cart',
          words: [
            'Website',
            'Select Another Class',
            'Select Class',
            'The cart is empty',
            'Sub-Total',
            'Invalid Coupon Code',
            'Apply',
            'Coupon Code',
            'Select Another Class',
            'Select Class',
            'The cart is empty',
            'Continue',
            'Discount',
            'Tax for tuition',
            'Total',
            'First Name',
            'Last Name',
            'Date of Birth',
            'Email',
            'Add Student',
            'Remove Coupon',
          ],
        },
      },
      {
        path: `${CART_URL.registration}/:id`,
        component: RegistrationPage,
        resolve: { translator: TranslatorResolver },
        data: {
          title: 'Registration',
          words: [
            'As a Student',
            'As a Group',
            'Sign in or Register',
            'You are almost done! We just need to know who you are.',
          ],
        },
      },
      {
        path: `${CART_URL.login}/:id`,
        component: LoginPage,
        resolve: { translator: TranslatorResolver },
        data: {
          title: 'Login',
          words: [
            'Student Registration',
            'Group Registration',
            'I am a returning student',
            'I am a new student',
            'I am a returning contact',
            'I am a new contact',
            'Username',
            'Please enter username.',
            'Password',
            'Please enter password.',
            'Sign In',
            'Forgot Password',
            'You are almost done! We just need to know who you are.',
            'Please sign in if you have already been a student with us, or enter your information below.',
            'Authentication failed. Please try again.',
          ],
        },
      },
      {
        path: `${CART_URL.update_student}/:id`,
        component: UpdateStudentPage,
        resolve: { translator: TranslatorResolver },
        data: {
          title: 'Update student information',
          words: [
            'Now, please update your contact information.',
            'We found your record',
            'is required.',
            'Select Another Class',
            'Submit',
          ],
        },
      },
      {
        path: `${CART_URL.create_account}/:id`,
        component: CreateAccountPage,
        resolve: { translator: TranslatorResolver },
        data: {
          title: 'Create account',
          words: [
            'Student Registration',
            'Group Registration',
            'I am a returning student',
            'I am a new student',
            'I am a returning contact',
            'I am a new contact',
            'Sign In',
            'Forgot Password',
            'Submit',
            'All input values are required',
            'You are almost done! We just need to know who you are.',
            'Please sign in if you have already been a student with us, or enter your information below.',
            'Username should be email address.',
            'Username and email address must be same.',
            'Input fields with asterisk (*) are required',
            'Confirm reset password',
            'You already have an account. If you forgot your password, we can email you a link to reset password. Would you like to reset password? (Yes / No)',
            'Yes',
            'No',
            'Invalid date.',
            'Password must be at least 8 characters long.',
            'This email already exists. Please use another email.',
            'Username exist, please try another one.',
            'Please enter only positive number.',
            'Please enter at least',
            'digits.',
            'Please enter no more than',
            'Please enter only number.',
            'Delete File',
            'Are you sure you wish to delete this attachment file?',
            'Delete',
            'Upload File',
            'Upload',
            'Close',
            'Please choose file to upload.',
            'Maximum file size should be 50MB.',
            'File size should be grater than 0.',
          ],
        },
      },
      {
        path: `${CART_URL.group_register}/:id`,
        component: AddStudentsPage,
        resolve: { translator: TranslatorResolver },
        data: {
          title: 'Add students',
          words: [
            'Add Student',
            'Register',
            'First Name',
            'Last Name',
            'Birth Date',
            'Home Phone',
            'Email',
            'Select Another Class',
            'Please add at least one student.',
            'Invalid date.',
            'Password must be at least 8 characters long.',
            'This email already exists. Please use another email.',
            'Username exist, please try another one.',
            'Please enter only positive number.',
            'Please enter at least',
            'digits.',
            'Please enter no more than',
            'Please enter only number.',
            'Delete File',
            'Are you sure you wish to delete this attachment file?',
            'Delete',
            'Upload File',
            'Upload',
            'Close',
            'Please choose file to upload.',
            'Maximum file size should be 50MB.',
            'File size should be grater than 0.',
          ],
        },
      },
      {
        path: `${CART_URL.request_password}/:id`,
        component: RequestPasswordPage,
        resolve: { translator: TranslatorResolver },
        data: {
          title: 'Forgot password',
          words: ['Email', 'Request Password', 'Submit', 'Back to Registration Page'],
        },
      },
      {
        path: `${CART_URL.checkout}/:id`,
        component: CheckoutPage,
        resolve: { translator: TranslatorResolver },
        data: {
          title: 'Checkout',
          words: [
            'You will be redirected to payment page to fill in personal information.',
            'Purchase',
            "Today's payment",
            'Total',
            'Other Charges',
            'Sub-Total',
            'Select Text Books or Other Charges',
            'Checkout',
            'Tax for tuition',
            'Discount',
            'Select Class',
            'Course Selected',
            'Courses Selected',
            'Course',
            'Show Less',
            'Show more additional info',
            'Due Date',
            'Amount',
          ],
        },
      },
      {
        path: `${CART_URL.billing}/:id`,
        component: BillingPage,
        resolve: { translator: TranslatorResolver },
        data: {
          title: 'Billing information',
          words: [
            'Back to your Cart',
            'Billing Information',
            'Contact Information',
            'Payment Information',
            'Transaction fee',
            'will be deducted from your account.',
            'Submit Payment',
            'Select the class again',
            'Esta transacción será procesada de forma segura gracias a la plataforma de',
            'Auto Charge agreement is required for installment payment.',
            'Purchase Order condition agreement is required.',
            'Please enter letters including ñ and space only.',
            'letters including ñ and space.',
            'Please enter only positive number.',
            'Please enter at least',
            'digits.',
            'Please enter no more than',
            'is required.',
            'Please enter only number.',
            'Delete File',
            'Are you sure you wish to delete this attachment file?',
            'Delete',
            'Upload File',
            'Upload',
            'Close',
            'Please choose file to upload.',
            'Maximum file size should be 50MB.',
            'File size should be grater than 0.',
          ],
        },
      },
      {
        path: `${CART_URL.thankyou}/:id`,
        component: ThankyouPage,
        data: {
          title: 'Thank you',
        },
      },
    ],
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class ShoppingCartRoutingModule {}
